######################### Eventum Configuration Example ########################

# =============================== API Parameters ===============================

# Whether to enable REST API
# Optional, default is true
api.enabled: true

# Bind address
# Optional, default is "0.0.0.0"
api.host: "0.0.0.0"

# Bind port for API
# Optional, default is 9474
api.port: 9474


# SSL parameters

# Whether to enable SSL
# Optional, default is true
api.ssl.enabled: true

# Verification mode of SSL connections
# Available value are "none", "optional", "required"
# Optional, default is "optional"
api.ssl.verify_mode: optional

# Absolute path to CA certificate
# Optional, default is null
api.ssl.ca_cert: null

# Absolute path to server certificate
# Optional, default is null
api.ssl.cert: null

# Absolute path to server certificate key
# Optional, default is null
api.ssl.cert_key: null

# User for basic auth
# Optional, default is "eventum"
api.auth.user: eventum

# Password for basic auth
# Optional, default is "eventum"
api.auth.password: eventum

# =========================== Generation Parameters ===========================

# Time zone for generating timestamps
# Available values are canonical timezone identifiers
# Optional, default is "UTC"
generation.timezone: UTC


# Batch parameters

# Batch size for generating events
# Optional, default is 10000
generation.batch.size: 10000

# Batch delay (in seconds) for generating events
# Optional, default is 1.0
generation.batch.delay: 1.0


# Queue parameters

# Maximum number of batches in timestamps queue
# Optional, default is 10
generation.queue.max_timestamp_batches: 10

# Maximum number of batches in events queue
# Optional, default is 10
generation.queue.max_event_batches: 10


# Whether to keep chronological order of timestamps by disabling output plugins
# concurrency
# Optional, default is false
generation.keep_order: false

# Maximum number of concurrent write operations performed by output plugins
# Optional, default is 100
generation.max_concurrency: 100

# Timeout (in seconds) before canceling single write task
# Optional, default is 10
generation.write_timeout : 10


# =============================== Log Parameters ==============================

# Log level
# Available value are "debug", "info", "warning", "error", "critical"
# Optional, default is "info"
log.level: info

# Format format
# Available options are "plain" and "json"
# Optional, default is "plain"
log.format: plain

# ============================== Path Parameters ==============================

# Absolute path to logs directory
# Required, there is no default value
path.logs: /app/logs/eventum/

# Absolute path to file with list of generators to run at startup
# Required, there is no default value
path.startup: /app/eventum/config/startup.yml

# Absolute path to directory with generators configuration files
# Required, there is no default value
path.generators_dir: /app/eventum/config/conf.d/

# Absolute path to keyring encrypted file with stored secrets
# Required, there is no default value
path.keyring_cryptfile: /app/eventum/config/cryptfile.cfg

# Filename for generator configurations. This parameter is used
# by the API for detection directories with generator
# configurations. Directory with generator configuration named
# other than this parameter value will not be operable using API
# endpoints.
# Optional, default is "generator.yml"
generator_config_filename: generator.yml
        