"""Models."""

from datetime import datetime

from pydantic import BaseModel


class AggregatedTimestamps(BaseModel):
    """Response model containing info about aggregated timestamps
    generated by input plugins.

    bin_edges : list[datetime]
        Timestamps representing edges of spans in aggregation histogram.

    bin_counts : list[int]
        Count of timestamps within span.
    """

    span_edges: list[datetime]
    span_counts: list[int]
