"""Models."""

from datetime import datetime

from pydantic import BaseModel


class AggregatedTimestamps(BaseModel, frozen=True, extra='forbid'):
    """Response model containing info about aggregated timestamps
    generated by input plugins.

    Attributes
    ----------
    span_edges : list[datetime]
        Timestamps representing edges of spans in aggregation histogram.

    span_counts : dict[int, list[int]]
        Count of timestamps within spans for each plugin id.

    """

    span_edges: list[datetime]
    span_counts: dict[int, list[int]]
